In [4]:
import torch

In [5]:
import numpy as np

In [8]:
arr=np.random.randn(3,5)

In [9]:
arr

array([[ 1.48069923,  0.62309255,  0.02661668, -1.74500014,  0.32326403],
       [-0.33181525, -2.31126872,  0.64364812, -2.21608731, -0.43773459],
       [ 0.13591703, -0.10578743, -0.27002668, -0.24649894,  0.12025166]])

In [10]:
tens=torch.from_numpy(arr)

In [11]:
tens

tensor([[ 1.4807,  0.6231,  0.0266, -1.7450,  0.3233],
        [-0.3318, -2.3113,  0.6436, -2.2161, -0.4377],
        [ 0.1359, -0.1058, -0.2700, -0.2465,  0.1203]], dtype=torch.float64)

In [12]:
another_tensor=torch.LongTensor([[2,4],[5,6]])

In [13]:
another_tensor

tensor([[2, 4],
        [5, 6]])

In [19]:
random_tensor=torch.randn((4,3))

## Variables

In [18]:
from torch.autograd import Variable
var_ex = Variable(torch.randn((4,3)))

## Autograd

In [20]:
from torch import FloatTensor
from torch.autograd import Variable


# Define the leaf nodes
a = Variable(FloatTensor([4]))

weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (2, 5, 9, 7)]

# unpack the weights for nicer assignment
w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
L = (10 - d)

L.backward()

for index, weight in enumerate(weights, start=1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to L: {gradient}")

Gradient of w1 w.r.t to L: -36.0
Gradient of w2 w.r.t to L: -28.0
Gradient of w3 w.r.t to L: -8.0
Gradient of w4 w.r.t to L: -20.0
